### ISSUE TITLE
Attempts to convert .js files in Assets/WebGLTemplates

### ISSUE THREAD

**Issue by JonathanHUnity** [Unity-Technologies/unityscript2csharp#1]
Repro:
- Add a .js file with garbage data to Assets/WebGLTemplates
- Run the tool on the project

Expected: The tool skips .js files in Assets/WebGLTemplates and its subdirectories
Actual: It attempts to convert these .js files

See https://docs.unity3d.com/Manual/webgl-templates.html

**Comment by adrianoc-unity3d** [comment]
Fixed
