### ISSUE TITLE
Convertion fails when using curry function

### ISSUE THREAD

**Issue by Limex0027** [Unity-Technologies/unityscript2csharp#10]
**Repro:**

- Add the following code to a .js script:
```
function Adapt(callback : function(int), value : int) : function()
{
	return function () { callback (value); };
}
```
- Then run the converter on the project.

**Expected:** Converting the script without errors.

**Actual:** Does not convert any scripts.
Gives the error:
"Internal compiler error: Object reference not set to an instance of an object.."

The same error is given with or without the use of the (-i) command.

**Comment by adrianoc-unity3d** [comment]
Fixed in 4d0ec1bc827e6c4f6a1c38833b1e05dfbacf2e00
