### ISSUE TITLE
Select only one script

### ISSUE THREAD

**Issue by mikorigames** [Unity-Technologies/unityscript2csharp#26]
I need to select and replace only one .js

**Comment by adrianoc-unity3d** [comment]
What exactly you mean? You want to be able to convert  one source (script) at a time? This may be possible with some small changes.

**Comment by mikorigames** [comment]
Yes exactly! I have a lot of script connected each other and if the conversion is not perfect i have a lot of errors. I need to convert one script at a time. Thanks

**Comment by adrianoc-unity3d** [comment]
Hi.

As of today we don't plan to support this.

As a side note, even though I understand your motivation it looks to me that trying to convert one script at a time will take much longer. 

My suggestion is to do the whole conversion (which, almost sure will not be 100% correct) and fix the issues in each source file listed in the console, from top to bottom.

**Comment by mikorigames** [comment]
Is it possible to have a tool to convert a js and having a c# text as result? I can create a c# manually and copy the result in it. It’s very important to convert one script at a time, even if i have to replace each script manually.

**Comment by adrianoc-unity3d** [comment]
If you really need to convert a script at a time, the easiest approach (IMO) is to change the converter so you can specify the path (perhaps, relative to your project root) of the script you want to convert. 

Besides changing the handling of the command line arguments, all you'll need to change is a callback that runs when we finish converting each source (this looks a lot like the **--dry-run** option, the main difference being that the **--dry-run** option ignores, i.e, does not save, all sources while your new command line argument would save a specific source).

That being said, from my experience either converting/helping other to convert some relatively big projects IMO this approach will be way harder.

Have you tried to run the converter in the whole project already? If so, have you tried to start fixing one source at a time? What are the issues you have hit?

**Comment by adrianoc-unity3d** [comment]
Realistically we'll not implement this.
