### ISSUE TITLE
I tried to use the unitypackage inside the 2018 editor and get this error

### ISSUE THREAD

**Issue by whimsica** [Unity-Technologies/unityscript2csharp#32]
I tried to use the unitypackage inside the 2018 osx editor and get this error:
Could not find file "/Applications/Unity/PlaybackEngines/LinuxStandaloneSupport/Variations/linux32_headless_development_mono/Data/Managed/UnityEditor.dll"

There is a file called UnityEngine.dll in that folder but not UnityEditor.dll

**Comment by adrianoc-unity3d** [comment]
Sorry not getting back before.  Are you still having this issue? If so, can you give more details? Exact version of Unity, which platform is currently selected, etc?

**Comment by adrianoc-unity3d** [comment]
Closing the issue since we haven't heard back from user

@whimsica, if you are still having this issue please, reopen the issue and try to add more details (for instance Editor.log)
