### ISSUE TITLE
Error CS0234 (missing type/namespace) in Unity 5.6.6f2

### ISSUE THREAD

**Issue by IsaiahKelly** [Unity-Technologies/unityscript2csharp#34]
Documentation here says Unity 5.6.x is preferred, but in Unity 5.6.6f2 I receive this error message after importing the package:

```
Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs(9,19): error CS0234: The type or namespace name `Compilation' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?
```
Opening the same project in Unity 2017.4.2f removes the error message. So maybe you should recommend Unity 2017.x instead of 5.6.x?

**Comment by adrianoc-unity3d** [comment]
Thanks for pointing out. I've updated the documentation recommending 2018.2.
