### ISSUE TITLE
in 5.6 there is no compilation dll - removing pointless references

### ISSUE THREAD

**Issue by twobob** [Unity-Technologies/unityscript2csharp#36]
![image](https://user-images.githubusercontent.com/915232/44690560-356acf80-aa53-11e8-9f2a-efdef4711f4c.png)

as pictured.  These can be elided. And one kills 5.6

**Comment by adrianoc-unity3d** [comment]
5.6 is not supported.  Recommend version is 2017.3 ~ 2018.1.

Anyway I've wrapped some of those usings with *if UNITY_2017_3_OR_NEWER * so we can show a descriptive message if you open this on Unity 2017.2 or older.
