### ISSUE TITLE
.Net framework 4.6.2 required?

### ISSUE THREAD

**Issue by twobob** [Unity-Technologies/unityscript2csharp#37]
![image](https://user-images.githubusercontent.com/915232/44690874-567ff000-aa54-11e8-979b-d528e8049323.png)

Hi. I run Windows 10, our corporate policy means we run under 4.6.1 and will for the forseeable.
Is building against 4.6.2 "required" internally in some way? some feature of it important over building for 4.6.1?

Anyway, thought I would ask. Since 5.6.x directs me to use the command line without checking the .net version. then the command line version also fails.

Doesn't look good. thanks

**Comment by adrianoc-unity3d** [comment]
Windows 10 (latest version) deploys .Net 4.7.2 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

Anyway, the converter builds on .Net 4.6.1 with no problem. I'll run more tests and will push a new version of the tool soon

**Comment by adrianoc-unity3d** [comment]
Just published a version that should work with 4.6,1
