### ISSUE TITLE
Failure to convert using the latest version on 2017.4.21

### ISSUE THREAD

**Issue by RunicPixels** [Unity-Technologies/unityscript2csharp#44]
**Issue :** 
Converting on the  v1.0.6991.18175 version of unityscript2csharp on Unity 2017.4.21f seems to give the following error, running from v1.0.6956.21054 doesn't appear to have this issues. The error cancels the porting process and leaves a nullpointer reference.

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Compilation.Assembly.<get_allReferences>m__0 (UnityEditor.Compilation.Assembly a) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:26)
System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[UnityEditor.Compilation.Assembly,System.String].MoveNext ()
System.Linq.Enumerable+<CreateConcatIterator>c__Iterator1`1[System.String].MoveNext ()
System.Collections.Generic.List`1[System.String].AddEnumerable (IEnumerable`1 enumerable) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:128)
System.Collections.Generic.List`1[System.String]..ctor (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:65)
System.Linq.Enumerable.ToArray[String] (IEnumerable`1 source)
UnityEditor.Compilation.Assembly.get_allReferences () (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:26)
UnityScript2CSharpRunner.<ComputeConverterCommandLineArguments>m__1 (UnityEditor.Compilation.Assembly a) (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:264)
System.Linq.Enumerable+<CreateSelectManyIterator>c__Iterator12`2[UnityEditor.Compilation.Assembly,System.String].MoveNext ()
System.Linq.Enumerable+<CreateWhereIterator>c__Iterator1D`1[System.String].MoveNext ()
System.Linq.Enumerable+<CreateDistinctIterator>c__Iterator3`1[System.String].MoveNext ()
UnityScript2CSharpRunner.ComputeConverterCommandLineArguments (Boolean verboseLogging) (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:268)
UnityScript2CSharpRunner.RunConverter (System.String converterPath) (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:180)
UnityScript2CSharpRunner.Convert () (at Assets/UnityScript2CSharp/Editor/UnityScript2CSharpRunner.cs:97)

**Specifications :** 
Unity 2017.4.21f, recently upgraded from 5.6.6f.
Running on Windows.

**Steps to reproduce :** 
Install Unity Package, Go to Tools, Run Conversion Tool both the convert and verbose convert options seems to give this error.

**Comment by adrianoc-unity3d** [comment]
Thanks for reporting.

It looks to be an issue in Unity Editor which has been fixed in 2018.1. Not sure if it was/will be port-backed to 2017.4. 

Depending on your project setup you may try to [revert this change](https://forum.unity.com/threads/unityscript-2-csharp-conversion-tool.487753/page-3#post-4236871) and give it a try (feel free to ask here if you need some help to do that)

btw: there were some discussions about this in [this forum thread](https://forum.unity.com/threads/unityscript-2-csharp-conversion-tool.487753/page-3#post-4252867).
