### ISSUE TITLE
Variable name string

### ISSUE THREAD

**Issue by Xian55** [Unity-Technologies/unityscript2csharp#51]
Using UnityScript2CSharp_1.0.7002.42237

Original JS Code
```js
function StringToBoolean(string : String) : boolean {
	return (string == '1');
}
```

Converted C# Code
```cs
public virtual bool StringToBoolean(string string)
{
    return string == "1";
}
```

Suggested Converted C# Code
```cs
public virtual bool StringToBoolean(string @string)
{
    return @string == "1";
}
```

Where the variable name conflicts with the C# primitive type

**Comment by adrianoc-unity3d** [comment]
>  UnityScript2CSharp_1.0.7002.42237

That is weird. I don't see this version in the release history.
Also, this should already be the case (we have tests for this):

https://github.com/Unity-Technologies/unityscript2csharp/blob/master/UnityScript2CSharp.Tests/Tests.cs#L624

Can you check with latest version: 
https://github.com/Unity-Technologies/unityscript2csharp/releases/tag/v1.0.7003.16529

**Comment by Xian55** [comment]
It works for param that will be @param, however the string failed.
I get around with it by renaming the varaibles.

**Comment by adrianoc-unity3d** [comment]
oh. I see. *string* is not in the list of *keywords* to be prefixed.
https://github.com/Unity-Technologies/unityscript2csharp/blob/master/UnityScript2CSharp/Steps/CSharpReservedKeywordIdentifierClashFix.cs

Sorry not realizing that before.

**Comment by adrianoc-unity3d** [comment]
https://github.com/Unity-Technologies/unityscript2csharp/tree/v1.0.7095.26335
