### ISSUE TITLE
Not compatible with Unity 2018.2(+)

### ISSUE THREAD

**Issue by comatose-turtle** [Unity-Technologies/unityscript2csharp#56]
Version 2018.1 is the most recent version supported, but there are many more recent versions now.
I've got Unity 2018.2.18f1, for instance, and therefore my project is already irreversibly updated past the supported version.  The package suggests using a supported version, but I don't see how I can follow that suggestion if I can't open my project in an earlier version.

Is there any intention of supporting newer versions?

**Comment by adrianoc** [comment]
Officially support for UnityScript was removed in 2018.2.0 whence there's no plan to support any version newer than 2018.1.

That being said I see that  2018.2.18f1 is still able to compile UnityScript sources.

Please, try to simply ignore the message from the converter and run it anyway (menu **Tools/Convert Project from UnityScript to C#**). I've tested with a simple script and it worked.

Let me know if this works for you.
