### ISSUE TITLE
How to run the tool in Unity 2019.1.9 from package, in Macos Mojave

### ISSUE THREAD

**Issue by jonathan81342** [Unity-Technologies/unityscript2csharp#57]
Newbie question: how to run the tool. I imported the package into 2019.1.9 and I see a unityscript2csharp asset, but there is no "Tools" menu to run it. My system is Macos Mojave.

**Comment by adrianoc-unity3d** [comment]
Unity 2018.1 is the latest version of Unity that is supported. You'll need to run with that version.

**Comment by jonathan81342** [comment]
Thank you!
