### ISSUE TITLE
Strange behaviour when converting UnityScript Time.time

### ISSUE THREAD

**Issue by CianNoonan** [Unity-Technologies/unityscript2csharp#7]
The following file will convert mostly fine except for C# line 51. The following issues occur

- timetemp is declared as an Object when it should be a float

- The if statement condition goes from `(Time.time > timetemp + LifeTime) `to` ((Time.time != 0f) > ((this.timetemp + this.LifeTime) != null))
`

Obviously this makes no sense, but it is easy to fix post import

Attached is the UnityScript, C# and meta for both: 
[Scripts.zip](https://github.com/Unity-Technologies/unityscript2csharp/files/1275213/Scripts.zip)

**Comment by adrianoc-unity3d** [comment]
The actual problem is not `Time.time` but the fact that `timetemp` is typed as `object` which is confusing the converter.

Probably the best option here would be to cast `timetemp` to `float` (something like):

`(Time.time > ((float) timetemp + LifeTime))`

**Comment by adrianoc-unity3d** [comment]
Fixed at 537625ae0041173beea1e94cfa1535f48a9d7bfb
