### ISSUE TITLE
Command window automatically closes when opened.

### ISSUE THREAD

**Issue by Limex0027** [Unity-Technologies/unityscript2csharp#8]
Hello,

I have downloaded the files and followed the [instructions](https://github.com/Unity-Technologies/unityscript2csharp). However whenever I try to use the "UnityScript2CSharp.exe", it starts the command window only to close it shortly after. It closes so fast that I don't have time to write in any commands to it.
My computer is running a Windows 7 and my version of Unity is Unity 5.6.1f1.

**Repro:**

- Download the tool from here: https://github.com/Unity-Technologies/unityscript2csharp/releases
(Version UnityScript2CSharp_1.0.6458.18187.zip)
- Extract the UnityScript2CSharp_1.0.6458.18187.zip file in a folder.
- Launch a new unity project.
- Create a JS script named Test.js with the following code in it:
`#pragma strict`
`function Update () {`
`	if(Input.GetKeyDown("a")){`
`		print("Hello");`
`	}`
`}`
- Make sure that the Anti-virus program has not blocked "UnityScript2CSharp.exe".
- Launch the "UnityScript2CSharp.exe" file. 
[Edit: launched the .exe file by double clicking on it]

**Expected:** A command window to open when launching the "UnityScript2CSharp.exe" file and to be able to convert the Test.js script to a Test.cs script.
**Actual:** Opens and closes the command window within 1-2 seconds automatically and the Test.js is not converted to CSharp.

**Comment by adrianoc-unity3d** [comment]
Have you run the conversion tool from a console?

What command line arguments have you passed ?

**Comment by Limex0027** [comment]
> Have you run the conversion tool from a console?

No. I have only tried to run it by double clicking on it.
> What command line arguments have you passed ?

I have not been able to pass any command lines yet, since the window closes before I have time to pass any command lines.

**Comment by Limex0027** [comment]
I have now tried to launch it through a console and I think I'm starting to understand how I'm supposed to pass commands through it.
Thank you for your help.
